% Generate Icosahedron data of radius R.
function [facedata,facesize] = Icosahedron(R)

% Icosahedron angle constants.
mAngle = atan(0.5);
sAngle  = pi * 2 / 5;

% Icosahedron coordinate constants.
Rsin  = R * sin(mAngle);
Rcos  = R * cos(mAngle);

% Icosahedron vertices.
% Organized into 3 separate groupings of 5 vertices each and two poles at
% either end.
verts = [[0;0;R],...
         [Rcos*sin(sAngle * ((0:4)-1));
          Rcos*cos(sAngle * ((0:4)-1));
          Rsin*ones(1,5)],...
         [Rcos*sin(sAngle * ((0:4)-0.5));
          Rcos*cos(sAngle * ((0:4)-0.5));
          -Rsin*ones(1,5)],...
         [0;0;-R]];

% Icosahedron faces.
% Organized into 20 groups of 3.
faces = [1,2,6,...
         1,3,2,...
         1,4,3,...
         1,5,4,...
         1,6,5,...
         2,11,6,...
         3,7,2,...
         4,8,3,...
         5,9,4,...
         6,10,5,...
         12,8,9,...
         12,9,10,...
         12,10,11,...
         12,11,7,...
         12,7,8,...
         8,4,9,...
         9,5,10,...
         10,6,11,...
         11,2,7,...
         7,3,8];

%Generate final data.
facedata = Solid(verts,faces);
facesize = 3 * ones(1,20);

end