function [facedata,facesize] = Cube(R)

verts = [-R,-R,-R,-R, R, R, R, R;
         -R,-R, R, R,-R,-R, R, R;
         -R, R,-R, R,-R, R,-R, R];
faces = [1,2,4,3,...
         6,5,7,8,...
         2,1,5,6,...
         3,4,8,7,...
         1,3,7,5,...
         4,2,6,8];
facedata = solid(verts,faces);
facesize = 4 * ones(1,6);
